### PR TITLE
Fix the mouse cursor flicker exhibited when entering reader mode

### PR DESCRIPTION
**Pull request by Xanfre**
This was a simpler fix than expected and brief testing yields no known side effects, with the middle-mouse reader mode functionality acting intended with no visible mouse cursor flickering.

### CODE REVIEW

**Comment by FenPhoenix** [comment]
Very clean. Just one change I would ask for: After each DefWndProc call, set Selectable back to true, so like this:

`                case InteropMisc.WM_MBUTTONDOWN:`
`                    this.SetStyle(ControlStyles.Selectable, false);`
`                    DefWndProc(ref m);`
`                    this.SetStyle(ControlStyles.Selectable, true);`
`                    break;`
`                case InteropMisc.WM_MBUTTONUP:`
`                    this.SetStyle(ControlStyles.Selectable, false);`
`                    DefWndProc(ref m);`
`                    this.SetStyle(ControlStyles.Selectable, true);`
`                    break;`
`                case InteropMisc.WM_MBUTTONDBLCLK:`
`                    this.SetStyle(ControlStyles.Selectable, false);`
`                    DefWndProc(ref m);`
`                    this.SetStyle(ControlStyles.Selectable, true);`
`                    break;`

Doing it like this, the flicker fix still works, but it also keeps the control selectable in case someone wants to use the Tab key to select it later (if you don't set Selectable back to true, it can never be keyboard-selected after the first middle-button click).

**Comment by FenPhoenix** [comment]
Great work on finding a fix so fast btw. Accepting.

**Comment by Xanfre** [comment]
Once I researched how reader mode works, it was fairly straightforward to implement a simple fix. With this, I believe the RichTextBox control AngelLoader uses has been improved to a point to where no major issues remain, which is an accomplishment given how _difficult_ it likes to be sometimes.

**Comment by FenPhoenix** [comment]
No prob. You've really helped improve the experience, appreciate it.

**Pull request merged**
